### PR TITLE
Change labels to only consider reviews from users with push access

### LINKED ISSUE #18: Only Approve with maintainer approval
In not sure if I would like this yet or not.

Would it be possible to only give the approved label if there has been a maintainer approval?

### PR DESCRIPTION
**Pull request by matt-fidd**
Fixes #18

### CODE REVIEW

**Comment by youngcw** [comment]
Seems fine.  Is there a way to test it?

**Comment by matt-fidd** [comment]
It's not the easiest, you'd need to pull it down, build, start, and follow the installation/usage/configuration instructions in the README to set up a github bot on your account, then create a test repo and install the bot there.

I've tested to make sure it works as expected.

**Comment by matt-fidd** [comment]
Updated to ignore non-push reviews regardless of type (as discussed in #18)

**Review by youngcw — APPROVED** [review]
The logic looks fine.  Ill approve for now if it's working in your test env.  It would still be nice if @twk3 could look it over.

**Review by twk3 — APPROVED** [review]
The change looks good to me as well. :+1:

**Comment by matt-fidd** [comment]
Looks like the review labels aren't working any more. They did work on my local tests so I can only assume that the setup of the actual repos is different.

Is there any way we can debug in-situ with netlify?

**Comment by twk3** [comment]
@matt-fidd yes, if you ask mattis for access, the logs are available here: https://app.netlify.com/sites/actual-gh-bot/logs/functions/webhooks (there aren't currently any errors being logged, just probot info messages).

```
Aug 14, 06:13:57 AM: d6585730 INFO (probot): loading app
Aug 14, 06:13:57 AM: d6585730 INFO (probot): probot loaded
Aug 14, 06:13:57 AM: d6585730 INFO (probot): webhook verified
Aug 14, 06:13:58 AM: d6585730 Duration: 1138.36 ms	Memory Usage: 144 MB	Init Duration: 454.96 ms
Aug 14, 07:12:40 AM: dac3cc79 INFO (probot): loading app
Aug 14, 07:12:40 AM: dac3cc79 INFO (probot): probot loaded
Aug 14, 07:12:40 AM: dac3cc79 INFO (probot): webhook verified
Aug 14, 07:12:42 AM: dac3cc79 Duration: 1027.19 ms	Memory Usage: 144 MB	Init Duration: 393.56 ms
Aug 14, 07:12:47 AM: 5053dae0 INFO (probot): loading app
Aug 14, 07:12:47 AM: 5053dae0 INFO (probot): probot loaded
Aug 14, 07:12:47 AM: 5053dae0 INFO (probot): webhook verified
Aug 14, 07:12:47 AM: 5053dae0 Duration: 905.84 ms	Memory Usage: 144 MB
Aug 14, 07:12:48 AM: 04987769 INFO (probot): loading app
Aug 14, 07:12:48 AM: 04987769 INFO (probot): probot loaded
Aug 14, 07:12:48 AM: 04987769 INFO (probot): webhook verified
Aug 14, 07:12:48 AM: 04987769 Duration: 7.81 ms	Memory Usage: 144 MB
Aug 14, 07:12:48 AM: 729346e4 INFO (probot): loading app
Aug 14, 07:12:48 AM: 729346e4 INFO (probot): probot loaded
Aug 14, 07:12:48 AM: 729346e4 INFO (probot): webhook verified
Aug 14, 07:12:48 AM: 729346e4 Duration: 4.40 ms	Memory Usage: 144 MB
```

**Comment by matt-fidd** [comment]
Thanks @twk3, I've asked on Discord.

Will get a PR up for extra logging quickly.

**Pull request merged**
